# Render.com deployment configuration
services:
  - type: web
    name: cropsense
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false # Set this in Render dashboard
    healthCheckPath: /health
    autoDeploy: true
    branch: main
